### PR TITLE
Dialogue

### PR DESCRIPTION
**Pull request by bobrk**
Add quotes to dialog and ran typogrify.

### CODE REVIEW

**Comment by acabal** [comment]
Can you rebase this against the dialogue branch to resolve the merge conflicts?

**Comment by acabal** [comment]
Also please make sure you only change the files that you were assigned... this commit touches a lot of other files and I think that's what's causing the merge conflicts.

**Comment by bobrk** [comment]
These are the files I touched: 

alain-rene-lesage_gil-blas_tobias-smollett(dialogue) > git status
On branch dialogue
Your branch is ahead of 'origin/dialogue' by 1 commit.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   src/epub/text/chapter-7-10.xhtml
	modified:   src/epub/text/chapter-7-11.xhtml
	modified:   src/epub/text/chapter-7-7.xhtml
	modified:   src/epub/text/chapter-7-8.xhtml
	modified:   src/epub/text/chapter-7-9.xhtml

no changes added to commit (use "git add" and/or "git commit -a")

Dunno what’s going on beyond that. I did run typogrify on the whole thing, but those files would have shown up on this list.

I’ll look some more when I have some time.

Bob

**Comment by acabal** [comment]
Were you able to sort this out? This is the last set left :)

**Comment by bobrk** [comment]
Without understanding what has happened, I will probably just back out my changes completely and try again.

**Comment by acabal** [comment]
OK, that's fine. If you want to do that then just delete your repo entirely and clone the dialogue branch fresh.

**Comment by bobrk** [comment]
I’ll figure it out tonight. The files with the merge issues were also my files, and it almost looks like my changes didn’t make it the first time, or they were rolled back from what I posted before.

**Pull request closed without merging**
